#!/usr/bin/env python3
"""
Generate sitemap-legacy.xml covering all HTML pages in public/ that
are NOT generated by Next.js (blog posts, YouTube transcripts, etc.).

This sitemap supplements the Next.js-generated sitemap.xml.
Run as part of the postbuild step.
"""

import re
from datetime import datetime
from pathlib import Path
from urllib.parse import quote

PUBLIC = Path(__file__).resolve().parent.parent / "next-site" / "public"
OUT = Path(__file__).resolve().parent.parent / "next-site" / "out"
SITE_URL = "https://www.julien.org"

# Directories to scan (relative to PUBLIC)
SCAN_DIRS = [
    "youtube",
    "blog/industry-perspectives",
    "blog/legacy-posts-and-images",
    "blog/aws-posts-and-images",
    "blog/huggingface-posts-and-images",
    "blog/arcee-posts",
]

# Skip these files (handled by Next.js sitemap or are redirects)
SKIP_FILES = {
    "blog/index.html",
    "youtube/index.html",
}


def extract_date_from_path(path_str: str) -> str:
    """Try to extract a date from the file path."""
    # Match YYYY-MM-DD or YYYYMMDD patterns
    m = re.search(r'(\d{4})-(\d{2})-(\d{2})', path_str)
    if m:
        return f"{m.group(1)}-{m.group(2)}-{m.group(3)}"
    m = re.search(r'/(\d{4})(\d{2})(\d{2})_', path_str)
    if m:
        return f"{m.group(1)}-{m.group(2)}-{m.group(3)}"
    # Year directory
    m = re.search(r'/(\d{4})/', path_str)
    if m:
        return f"{m.group(1)}-12-31"
    return datetime.now().strftime("%Y-%m-%d")


def get_priority(rel_path: str) -> str:
    """Assign priority based on content type."""
    if "/index.html" in rel_path:
        return "0.6"
    if "industry-perspectives" in rel_path:
        return "0.6"
    if "youtube" in rel_path:
        return "0.4"
    return "0.5"


def get_changefreq(rel_path: str) -> str:
    """Assign change frequency."""
    if "/index.html" in rel_path:
        return "monthly"
    return "yearly"


def generate():
    urls = []

    for scan_dir in SCAN_DIRS:
        dir_path = PUBLIC / scan_dir
        if not dir_path.exists():
            continue

        for html_file in sorted(dir_path.rglob("*.html")):
            rel_path = str(html_file.relative_to(PUBLIC))

            if rel_path in SKIP_FILES:
                continue

            # URL-encode the path (handle spaces etc.)
            encoded_path = "/".join(quote(part, safe="") for part in rel_path.split("/"))
            url = f"{SITE_URL}/{encoded_path}"
            lastmod = extract_date_from_path(rel_path)
            priority = get_priority(rel_path)
            changefreq = get_changefreq(rel_path)

            urls.append((url, lastmod, changefreq, priority))

    # Generate XML
    xml_parts = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ]

    for url, lastmod, changefreq, priority in urls:
        xml_parts.append(f"  <url>")
        xml_parts.append(f"    <loc>{url}</loc>")
        xml_parts.append(f"    <lastmod>{lastmod}</lastmod>")
        xml_parts.append(f"    <changefreq>{changefreq}</changefreq>")
        xml_parts.append(f"    <priority>{priority}</priority>")
        xml_parts.append(f"  </url>")

    xml_parts.append("</urlset>")
    xml_content = "\n".join(xml_parts) + "\n"

    # Write to both public/ and out/
    for target_dir in [PUBLIC, OUT]:
        target = target_dir / "sitemap-legacy.xml"
        target.write_text(xml_content, encoding="utf-8")
        print(f"  Written {len(urls)} URLs to {target}")

    return len(urls)


if __name__ == "__main__":
    n = generate()
    print(f"\nGenerated sitemap-legacy.xml with {n} URLs")
